### ISSUE TITLE
Dabbamisan

### ISSUE THREAD

**Issue by muhammadjonqilichev** [ErkinovDavlatyor/namanganliklar24#1]
![no](https://user-images.githubusercontent.com/83636700/123748103-30968c00-d8cd-11eb-8ccd-97750928e17f.png)
bu qara

**Comment by ErkinovDavlatyor** [comment]
yoqaley

**Comment by muhammadjonqilichev** [comment]
fffffff

**Comment by ErkinovDavlatyor** [comment]
bore
